# rename this file to config.yaml before start

# qqbot account, not needed anymore for qrcode authentication
account:  1914430989
password: "zhu305750624"

# server to view verification code, not required for mac
port: 3100
host: localhost

# message handling, ignore offline message 20 min ago
# offline_msg_keeptime: 1200

# plugin list
plugins:
    - help
    - debug
    - apiserver
    - moxiaoxiao
    - koudai

# apiserver plugin configration
api_port:  3200
api_token: ''
