// Generated by CoffeeScript 1.10.0

/*
  default behavior: log chat logs to file
  @command top (count) (chat-lines): show group's chat ranks in (count) depends on recently (chat-lines) history.
  need configs:
  -
 */

/**
message:{ content: '还好',
  time: Sat Apr 09 2016 01:45:08 GMT+0800 (CST),
  from_uin: 2875147139,
  type: 'message',
  uid: 3083,
  from_user:
   { face: 318,
     flag: 289440320,
     nick: '墨小水',
     uin: 2875147139,
     account: 747979327 } }
*/
(function() {
    module.exports = function(content, send, robot, message) {
        var log = new(require('log'))('debug');
        log.debug('[log]message:', message);
        log.debug('[log]content:', content);
        return "nothing";
    };

}).call(this);
