// Generated by CoffeeScript 1.10.0

/*
  default behavior: log chat logs to file
  @command top (count) (chat-lines): show group's chat ranks in (count) depends on recently (chat-lines) history.
  need configs:
  -
 */

/**
message:{ content: '还好',
  time: Sat Apr 09 2016 01:45:08 GMT+0800 (CST),
  from_uin: 2875147139,
  type: 'message',
  uid: 3083,
  from_user:
   { face: 318,
     flag: 289440320,
     nick: '墨小水',
     uin: 2875147139,
     account: 747979327 } }
*/

(function() {

    var rq = require('request-promise');
    var log = new(require('log'))('debug');
    var cron = require('node-cron');

    function getTask(rule, qqId, qqbot) {
        return cron.schedule(rule, function() {
            log.debug('koudai schedule');
            rq({
                method: 'GET',
                uri: 'http://i.sojex.net/FinanceQuoteServer/client.action/GetUserFocusMessage',
                qs: {
                    accessToken: '973b1a4ec95cbcce4690c44826b4a2db9680d1240a3ca06f9fadb7322b730e6b'
                },
                json: true
            }).then(function(json) {
                var firstItem = json.data.list[0];
                var timestamp = new Date().getTime();
                var timeStep = timestamp - firstItem.time;
                if (timeStep < 5*60*1000) {
                    qqbot.get_group_gid(qqId, function(err, gid) {
                        return qqbot.send_message_to_group(gid, firstItem.content, function(ret, e) {});
                    });
                }
            });
        }, false);
    }

    var task;
    exports.init = function(qqbot) {
        task = getTask("*/5 * * * *", "303227871", qqbot);
        return task.start();
    };
    exports.stop = function(qqbot) {
        return task.stop();
    };
}).call(this);
