// Generated by CoffeeScript 1.10.0

/*
  default behavior: log chat logs to file
  @command top (count) (chat-lines): show group's chat ranks in (count) depends on recently (chat-lines) history.
  need configs:
  -
 */

/**
message:{ content: '还好',
  time: Sat Apr 09 2016 01:45:08 GMT+0800 (CST),
  from_uin: 2875147139,
  type: 'message',
  uid: 3083,
  from_user:
   { face: 318,
     flag: 289440320,
     nick: '墨小水',
     uin: 2875147139,
     account: 747979327 } }
*/

(function() {

    var rq = require('request-promise');
    var log = new(require('log'))('debug');

    var requestTuling = function(text, uuid) {
        return rq({
                method: 'GET',
                uri: "http://www.tuling123.com/openapi/api",
                qs: {
                    key: 'e69fad88720627b2eaa67d0278800bc6',
                    info: text,
                    userid: uuid
                },
                json: true
            })
            .then(function(data) {
                if (data.code === 100000) {
                    return {
                        text: data.text,
                        type: -1,
                    };
                } else if (data.code === 200000) {
                    return {
                        text: data.text,
                        linkList: [{
                            title: data.text,
                            url: data.url,
                        }],
                        type: -1,
                    };
                } else if (data.code === 302000) {
                    return {
                        text: data.text,
                        linkList: data.list.map(function(item) {
                            return {
                                title: "【" + item.source + "】" + item.article,
                                image: item.icon,
                                url: item.detailurl
                            };
                        }),
                        type: -1
                    };
                } else if (data.code === 305000) {
                    return {
                        text: data.text,
                        linkList: data.list.map(function(item) {
                            return {
                                title: item.trainnum,
                                desc: item.start + "->" + item.terminal + "(" + item.starttime + "-" + item.endtime + ")",
                                image: item.icon,
                                url: item.detailurl
                            };
                        }),
                        type: -1
                    };
                } else if (data.code === 306000) {
                    return {
                        text: data.text,
                        linkList: data.list.map(function(item) {
                            return {
                                title: item.flight,
                                desc: "(" + item.starttime + "-" + item.endtime + ")",
                                image: item.icon,
                                url: item.detailurl
                            };
                        }),
                        type: -1
                    };
                } else if (data.code === 308000) {
                    return {
                        text: data.text,
                        linkList: data.list.map(function(item) {
                            return {
                                title: item.name,
                                desc: item.info,
                                image: item.icon,
                                url: item.detailurl
                            };
                        }),
                        type: -1
                    };
                } else {
                    throw new Error("数据出错");
                }
            });
    };
    module.exports = function(content, send, robot, message) {
        if (message.type == "group_message") {
            if (content.match(/^墨小小$/i)) {
                send("你好我是墨小小");
            } else if (ret = content.match(/墨小小/i)) {
                content = content.replace("墨小小", "");
                requestTuling(content, message.from_user.account)
                    .then(function(reply) {
                        send(reply.text);
                    }).catch(function(error) {
                        log.debug('[moxiaoxiao]', error.message);
                    });
            }
        } else if (message.type == "message") {
            requestTuling(content, message.from_user.account)
                .then(function(reply) {
                    send(reply.text);
                }).catch(function(error) {
                    log.debug('[moxiaoxiao]', error.message);
                });
        }
    };
}).call(this);
